version: '3'
services:
  app:
    image: davide92/spring-example1
    ports:
      - 8080:8080
  mysqldb:
    image: mysql-custom
    ports:
      - 3307:3306
    volumes:
      - mysql-test-data:/var/lib/mysql
volumes:
  mysql-test-data:
    driver: local
